### ISSUE TITLE
ee468d7 breaks ACGLogReader

### ISSUE THREAD

**Issue by KonstantinHoffmann** [tgvaughan/bacter#31]
I think that ee468d7 causes bacter.util.BacterACGLogReader to produce errors. 

Minimal Test case (with ACGs simulated from bacter/examplesACGsimulations/simulateACGs2taxon.xml) :

```
import java.io.File;
import java.io.IOException;

import bacter.ConversionGraph;
import bacter.util.BacterACGLogReader;

public class Test {

	public static void main(String[] args) throws IOException {
		BacterACGLogReader bacterLog = new BacterACGLogReader(new File("bacter/examples/ACGsimulations/simulateACGs2taxon.trees"),0.0);
		ConversionGraph g = bacterLog.iterator().next();
	}

}
```

produces:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
	at beast.evolution.tree.Tree.setRoot(Tree.java:316)
	at bacter.ConversionGraph.fromExtendedNewick(ConversionGraph.java:946)
	at bacter.ConversionGraph.fromExtendedNewick(ConversionGraph.java:723)
	at bacter.util.BacterACGLogReader$1.next(BacterACGLogReader.java:323)
	at bacter.util.BacterACGLogReader$1.next(BacterACGLogReader.java:1)
	at Test.main(Test.java:11)
```

I think the problem is that the iterator initializes an acg and with it the `m_nodes` array. However the `setRoot()` method expects the m_nodes array being either initialized with the correct amount of nodes or null.

**Comment by tgvaughan** [comment]
Thanks @KonstantinHoffmann, this should be fixed by 49fa34f7b7192023db343d0a79642c013a78f32e and in the latest release.  (Essentially the previous deserialization fix was broken.)  I've added in a unit test to hopefully avoid further regressions.
